### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Samgarr** [jrnewell/spotify-ripper#211]
Hello, i am trying download playlist 
`spotify-ripper -u username --playlist-sync -k ~/pathto/spotify_appkey.key "spotify:user:username:playlist:7j9Ifn0ITlPa3SF7vjTgFd"`

but i'm ending with this:
`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 235, in run
    self.progress.calc_total(all_tracks)
  File "/usr/lib/python2.7/site-packages/spotify_ripper/progress.py", line 71, in calc_total
    if not self.args.overwrite and path_exists(audio_file) and \
  File "/usr/lib/python2.7/site-packages/spotify_ripper/utils.py", line 34, in path_exists
    return os.path.exists(enc_str(path))
  File "/usr/lib/python2.7/site-packages/spotify_ripper/utils.py", line 30, in enc_str
    return _str.encode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'`

Ripping tracks works fine.

`$ python2.7 -V
Python 2.7.11
`
`$ uname -a
Linux wrk 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux`

`$ spotify-ripper -V
2.8.8
`

**Comment by zomed** [comment]
Hello,

Having the exact same issue here after updating to 2.8.8 via pip.

For the time being I just downgraded via pip to 2.8.6, which was working fine for me: pip install spotify-ripper==2.8.6

**Comment by asoretmadolell** [comment]
Same thing happens to me! I'm running version 2.8.8, Python 2.7.10, and Ubuntu 15.10

**Comment by jrnewell** [comment]
Sorry, think I fixed this issue in ``2.8.9``.

**Comment by asoretmadolell** [comment]
Confirmed, I've had no problems up until now ripping playlists using 2.8.9.
Thank you so much!
