### ISSUE TITLE
Error code after loading playlist

### ISSUE THREAD

**Issue by wessel145** [jrnewell/spotify-ripper#197]
Hi, since i upgraded to 2.8.5 i get the following error code after loading a bunch of playlists

`Loading playlist...
Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 226, in run
    self.progress.calc_total(all_tracks)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/progress.py", line 69, in calc_total
    not is_partial(audio_file, track):
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 399, in is_partial
    audio_file_dur = audio_file_duration(audio_file)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 394, in audio_file_duration
    _file = mutagen.File(audio_file)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 184, in File
    from mutagen.asf import ASF
  File "/usr/local/lib/python2.7/dist-packages/mutagen/asf/__init__.py", line 14, in <module>
    from mutagen._util import resize_bytes, DictMixin
ImportError: cannot import name resize_bytes
`

since i'm not that pro in linux i have no clue :(
